apiVersion: v1
entries:
  headwind:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Initial Helm chart release
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://headwind.sh/docs
        - name: GitHub
          url: https://github.com/headwind-sh/headwind
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Seamless Upgrades
      artifacthub.io/prerelease: "false"
      artifacthub.io/recommendations: |
        - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      artifacthub.io/signKey: |
        fingerprint: <placeholder>
        url: https://headwind.sh/pgp-key.txt
    apiVersion: v2
    appVersion: 0.1.0
    created: "2025-11-10T21:43:40.470093364Z"
    description: A Kubernetes operator to automate workload updates based on container
      image changes
    digest: 755d8fbf10a6189e08415de1765d837496a5d2cbc3a9c1b71668ed1e56a42e99
    home: https://headwind.sh
    icon: https://headwind.sh/img/logo.svg
    keywords:
    - kubernetes
    - operator
    - automation
    - gitops
    - ci-cd
    - image-updates
    - helm
    maintainers:
    - name: Headwind Contributors
      url: https://github.com/headwind-sh/headwind
    name: headwind
    sources:
    - https://github.com/headwind-sh/headwind
    type: application
    urls:
    - https://headwind.sh/charts/headwind-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-10T21:43:40.467824343Z"
