apiVersion: v1
kind: ServiceAccount
metadata:
  name: headwind
  namespace: headwind-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headwind
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headwind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headwind
subjects:
- kind: ServiceAccount
  name: headwind
  namespace: headwind-system
