{{- if .Values.rbac.create -}}
apiVersion: {{ include "headwind.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "headwind.fullname" . }}
  labels:
    {{- include "headwind.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "headwind.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "headwind.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
