{{- if and .Values.observability.create .Values.observability.influxdb.enabled .Values.observability.influxdb.ingress.enabled -}}
apiVersion: {{ include "headwind.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "headwind.fullname" . }}-influxdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headwind.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
  {{- with .Values.observability.influxdb.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.observability.influxdb.ingress.className }}
  ingressClassName: {{ .Values.observability.influxdb.ingress.className }}
  {{- end }}
  {{- if .Values.observability.influxdb.ingress.tls }}
  tls:
    {{- range .Values.observability.influxdb.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.observability.influxdb.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "headwind.fullname" $ }}-influxdb
                port:
                  number: 8086
              {{- else }}
              serviceName: {{ include "headwind.fullname" $ }}-influxdb
              servicePort: 8086
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
