{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "headwind.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "headwind.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headwind.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "headwind.fullname" $ }}
                port:
                  {{- if eq .backend "webhook" }}
                  number: {{ $.Values.service.webhookPort }}
                  {{- else if eq .backend "api" }}
                  number: {{ $.Values.service.apiPort }}
                  {{- else if eq .backend "ui" }}
                  number: {{ $.Values.service.uiPort }}
                  {{- else if eq .backend "metrics" }}
                  number: {{ $.Values.service.metricsPort }}
                  {{- else }}
                  number: {{ $.Values.service.uiPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ include "headwind.fullname" $ }}
              {{- if eq .backend "webhook" }}
              servicePort: {{ $.Values.service.webhookPort }}
              {{- else if eq .backend "api" }}
              servicePort: {{ $.Values.service.apiPort }}
              {{- else if eq .backend "ui" }}
              servicePort: {{ $.Values.service.uiPort }}
              {{- else if eq .backend "metrics" }}
              servicePort: {{ $.Values.service.metricsPort }}
              {{- else }}
              servicePort: {{ $.Values.service.uiPort }}
              {{- end }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
