{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "headwind.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headwind.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "headwind.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  - Egress
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
