{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "headwind.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headwind.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
